//go:build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 David Picillo

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerStatus) DeepCopyInto(out *ContainerStatus) {
	*out = *in
	if in.Rounds != nil {
		in, out := &in.Rounds, &out.Rounds
		*out = make([]RoundStat, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerStatus.
func (in *ContainerStatus) DeepCopy() *ContainerStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CutoverStatus) DeepCopyInto(out *CutoverStatus) {
	*out = *in
	if in.SourceDeletedAt != nil {
		in, out := &in.SourceDeletedAt, &out.SourceDeletedAt
		*out = (*in).DeepCopy()
	}
	if in.EndpointBridge != nil {
		in, out := &in.EndpointBridge, &out.EndpointBridge
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EndpointBridgeAt != nil {
		in, out := &in.EndpointBridgeAt, &out.EndpointBridgeAt
		*out = (*in).DeepCopy()
	}
	if in.TargetPodCreatedAt != nil {
		in, out := &in.TargetPodCreatedAt, &out.TargetPodCreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ReplacementRequestedAt != nil {
		in, out := &in.ReplacementRequestedAt, &out.ReplacementRequestedAt
		*out = (*in).DeepCopy()
	}
	if in.InterceptArmedAt != nil {
		in, out := &in.InterceptArmedAt, &out.InterceptArmedAt
		*out = (*in).DeepCopy()
	}
	if in.InterceptedAt != nil {
		in, out := &in.InterceptedAt, &out.InterceptedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CutoverStatus.
func (in *CutoverStatus) DeepCopy() *CutoverStatus {
	if in == nil {
		return nil
	}
	out := new(CutoverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Migration) DeepCopyInto(out *Migration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Migration.
func (in *Migration) DeepCopy() *Migration {
	if in == nil {
		return nil
	}
	out := new(Migration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Migration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationList) DeepCopyInto(out *MigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Migration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationList.
func (in *MigrationList) DeepCopy() *MigrationList {
	if in == nil {
		return nil
	}
	out := new(MigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSpec) DeepCopyInto(out *MigrationSpec) {
	*out = *in
	in.PreCopy.DeepCopyInto(&out.PreCopy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSpec.
func (in *MigrationSpec) DeepCopy() *MigrationSpec {
	if in == nil {
		return nil
	}
	out := new(MigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationStatus) DeepCopyInto(out *MigrationStatus) {
	*out = *in
	in.Network.DeepCopyInto(&out.Network)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Source.DeepCopyInto(&out.Source)
	in.Target.DeepCopyInto(&out.Target)
	if in.PhantomNodes != nil {
		in, out := &in.PhantomNodes, &out.PhantomNodes
		*out = make(map[string]v1.MicroTime, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PhantomUnroutable != nil {
		in, out := &in.PhantomUnroutable, &out.PhantomUnroutable
		*out = make(map[string]v1.MicroTime, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.Timings = in.Timings
	in.Cutover.DeepCopyInto(&out.Cutover)
	if in.PhaseChangedAt != nil {
		in, out := &in.PhaseChangedAt, &out.PhaseChangedAt
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.ReleasedAt != nil {
		in, out := &in.ReleasedAt, &out.ReleasedAt
		*out = (*in).DeepCopy()
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationStatus.
func (in *MigrationStatus) DeepCopy() *MigrationStatus {
	if in == nil {
		return nil
	}
	out := new(MigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	if in.PoolPreparedAt != nil {
		in, out := &in.PoolPreparedAt, &out.PoolPreparedAt
		*out = (*in).DeepCopy()
	}
	if in.ReannouncedAt != nil {
		in, out := &in.ReannouncedAt, &out.ReannouncedAt
		*out = (*in).DeepCopy()
	}
	if in.PoolRotatedAt != nil {
		in, out := &in.PoolRotatedAt, &out.PoolRotatedAt
		*out = (*in).DeepCopy()
	}
	if in.PhantomClusterCIDRs != nil {
		in, out := &in.PhantomClusterCIDRs, &out.PhantomClusterCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhantomFlow) DeepCopyInto(out *PhantomFlow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhantomFlow.
func (in *PhantomFlow) DeepCopy() *PhantomFlow {
	if in == nil {
		return nil
	}
	out := new(PhantomFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreCopySpec) DeepCopyInto(out *PreCopySpec) {
	*out = *in
	if in.AutoConverge != nil {
		in, out := &in.AutoConverge, &out.AutoConverge
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreCopySpec.
func (in *PreCopySpec) DeepCopy() *PreCopySpec {
	if in == nil {
		return nil
	}
	out := new(PreCopySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoundStat) DeepCopyInto(out *RoundStat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoundStat.
func (in *RoundStat) DeepCopy() *RoundStat {
	if in == nil {
		return nil
	}
	out := new(RoundStat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePhantom) DeepCopyInto(out *SourcePhantom) {
	*out = *in
	if in.Flows != nil {
		in, out := &in.Flows, &out.Flows
		*out = make([]PhantomFlow, len(*in))
		copy(*out, *in)
	}
	if in.OldBoundListeners != nil {
		in, out := &in.OldBoundListeners, &out.OldBoundListeners
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.UDPServerPorts != nil {
		in, out := &in.UDPServerPorts, &out.UDPServerPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePhantom.
func (in *SourcePhantom) DeepCopy() *SourcePhantom {
	if in == nil {
		return nil
	}
	out := new(SourcePhantom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceStatus) DeepCopyInto(out *SourceStatus) {
	*out = *in
	if in.ReadyToFreezeAt != nil {
		in, out := &in.ReadyToFreezeAt, &out.ReadyToFreezeAt
		*out = (*in).DeepCopy()
	}
	if in.FrozenAt != nil {
		in, out := &in.FrozenAt, &out.FrozenAt
		*out = (*in).DeepCopy()
	}
	if in.HandOverAt != nil {
		in, out := &in.HandOverAt, &out.HandOverAt
		*out = (*in).DeepCopy()
	}
	if in.TransferDoneAt != nil {
		in, out := &in.TransferDoneAt, &out.TransferDoneAt
		*out = (*in).DeepCopy()
	}
	if in.ThawedAt != nil {
		in, out := &in.ThawedAt, &out.ThawedAt
		*out = (*in).DeepCopy()
	}
	if in.Phantom != nil {
		in, out := &in.Phantom, &out.Phantom
		*out = new(SourcePhantom)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceStatus.
func (in *SourceStatus) DeepCopy() *SourceStatus {
	if in == nil {
		return nil
	}
	out := new(SourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetContainerStatus) DeepCopyInto(out *TargetContainerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetContainerStatus.
func (in *TargetContainerStatus) DeepCopy() *TargetContainerStatus {
	if in == nil {
		return nil
	}
	out := new(TargetContainerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetPhantom) DeepCopyInto(out *TargetPhantom) {
	*out = *in
	if in.ProgrammedAt != nil {
		in, out := &in.ProgrammedAt, &out.ProgrammedAt
		*out = (*in).DeepCopy()
	}
	if in.DeadFlows != nil {
		in, out := &in.DeadFlows, &out.DeadFlows
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.ReleasedAt != nil {
		in, out := &in.ReleasedAt, &out.ReleasedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetPhantom.
func (in *TargetPhantom) DeepCopy() *TargetPhantom {
	if in == nil {
		return nil
	}
	out := new(TargetPhantom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetStatus) DeepCopyInto(out *TargetStatus) {
	*out = *in
	if in.PreAttachedVolumes != nil {
		in, out := &in.PreAttachedVolumes, &out.PreAttachedVolumes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SandboxReadyAt != nil {
		in, out := &in.SandboxReadyAt, &out.SandboxReadyAt
		*out = (*in).DeepCopy()
	}
	if in.AddressReadyAt != nil {
		in, out := &in.AddressReadyAt, &out.AddressReadyAt
		*out = (*in).DeepCopy()
	}
	if in.SandboxStagedAt != nil {
		in, out := &in.SandboxStagedAt, &out.SandboxStagedAt
		*out = (*in).DeepCopy()
	}
	if in.RestoreStartedAt != nil {
		in, out := &in.RestoreStartedAt, &out.RestoreStartedAt
		*out = (*in).DeepCopy()
	}
	if in.RestoredAt != nil {
		in, out := &in.RestoredAt, &out.RestoredAt
		*out = (*in).DeepCopy()
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]TargetContainerStatus, len(*in))
		copy(*out, *in)
	}
	if in.Phantom != nil {
		in, out := &in.Phantom, &out.Phantom
		*out = new(TargetPhantom)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStatus.
func (in *TargetStatus) DeepCopy() *TargetStatus {
	if in == nil {
		return nil
	}
	out := new(TargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timings) DeepCopyInto(out *Timings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timings.
func (in *Timings) DeepCopy() *Timings {
	if in == nil {
		return nil
	}
	out := new(Timings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeStatus) DeepCopyInto(out *VolumeStatus) {
	*out = *in
	if in.DetachedAt != nil {
		in, out := &in.DetachedAt, &out.DetachedAt
		*out = (*in).DeepCopy()
	}
	if in.AttachedAt != nil {
		in, out := &in.AttachedAt, &out.AttachedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeStatus.
func (in *VolumeStatus) DeepCopy() *VolumeStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeStatus)
	in.DeepCopyInto(out)
	return out
}
