// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 David Picillo

// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package phantom

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type phantomCtl struct {
	_       structs.HostLayout
	Enabled uint32
}

type phantomXlKey struct {
	_      structs.HostLayout
	Scope  uint8
	Proto  uint8
	Family uint8
	Pad    uint8
	Sport  uint16
	Dport  uint16
	Saddr  [16]uint8
	Daddr  [16]uint8
}

type phantomXlVal struct {
	_             structs.HostLayout
	Saddr         [16]uint8
	Daddr         [16]uint8
	Sport         uint16
	Dport         uint16
	Flags         uint32
	TunnelRemote4 uint32
	Owner         uint32
	Packets       uint64
	LastSeenNs    uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	phantomMapPaguroXlCtl   = "paguro_xl_ctl"
	phantomMapPaguroXlIn    = "paguro_xl_in"
	phantomMapPaguroXlOut   = "paguro_xl_out"
	phantomMapPaguroXlStats = "paguro_xl_stats"
	phantomProgXlHostIn     = "xl_host_in"
	phantomProgXlHostLocal  = "xl_host_local"
	phantomProgXlHostOut    = "xl_host_out"
	phantomProgXlPodIn      = "xl_pod_in"
	phantomProgXlPodOut     = "xl_pod_out"
	phantomProgXlPodhostOut = "xl_podhost_out"
	phantomVarCfgL3Off      = "cfg_l3_off"
)

// loadPhantom returns the embedded CollectionSpec for phantom.
func loadPhantom() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PhantomBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load phantom: %w", err)
	}

	return spec, err
}

// loadPhantomObjects loads phantom and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*phantomObjects
//	*phantomPrograms
//	*phantomMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPhantomObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPhantom()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// phantomSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type phantomSpecs struct {
	phantomProgramSpecs
	phantomMapSpecs
	phantomVariableSpecs
}

// phantomProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type phantomProgramSpecs struct {
	XlHostIn     *ebpf.ProgramSpec `ebpf:"xl_host_in"`
	XlHostLocal  *ebpf.ProgramSpec `ebpf:"xl_host_local"`
	XlHostOut    *ebpf.ProgramSpec `ebpf:"xl_host_out"`
	XlPodIn      *ebpf.ProgramSpec `ebpf:"xl_pod_in"`
	XlPodOut     *ebpf.ProgramSpec `ebpf:"xl_pod_out"`
	XlPodhostOut *ebpf.ProgramSpec `ebpf:"xl_podhost_out"`
}

// phantomMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type phantomMapSpecs struct {
	PaguroXlCtl   *ebpf.MapSpec `ebpf:"paguro_xl_ctl"`
	PaguroXlIn    *ebpf.MapSpec `ebpf:"paguro_xl_in"`
	PaguroXlOut   *ebpf.MapSpec `ebpf:"paguro_xl_out"`
	PaguroXlStats *ebpf.MapSpec `ebpf:"paguro_xl_stats"`
}

// phantomVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type phantomVariableSpecs struct {
	CfgL3Off *ebpf.VariableSpec `ebpf:"cfg_l3_off"`
}

// phantomObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPhantomObjects or ebpf.CollectionSpec.LoadAndAssign.
type phantomObjects struct {
	phantomPrograms
	phantomMaps
	phantomVariables
}

func (o *phantomObjects) Close() error {
	return _PhantomClose(
		&o.phantomPrograms,
		&o.phantomMaps,
	)
}

// phantomMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPhantomObjects or ebpf.CollectionSpec.LoadAndAssign.
type phantomMaps struct {
	PaguroXlCtl   *ebpf.Map `ebpf:"paguro_xl_ctl"`
	PaguroXlIn    *ebpf.Map `ebpf:"paguro_xl_in"`
	PaguroXlOut   *ebpf.Map `ebpf:"paguro_xl_out"`
	PaguroXlStats *ebpf.Map `ebpf:"paguro_xl_stats"`
}

func (m *phantomMaps) Close() error {
	return _PhantomClose(
		m.PaguroXlCtl,
		m.PaguroXlIn,
		m.PaguroXlOut,
		m.PaguroXlStats,
	)
}

// phantomVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPhantomObjects or ebpf.CollectionSpec.LoadAndAssign.
type phantomVariables struct {
	CfgL3Off *ebpf.Variable `ebpf:"cfg_l3_off"`
}

// phantomPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPhantomObjects or ebpf.CollectionSpec.LoadAndAssign.
type phantomPrograms struct {
	XlHostIn     *ebpf.Program `ebpf:"xl_host_in"`
	XlHostLocal  *ebpf.Program `ebpf:"xl_host_local"`
	XlHostOut    *ebpf.Program `ebpf:"xl_host_out"`
	XlPodIn      *ebpf.Program `ebpf:"xl_pod_in"`
	XlPodOut     *ebpf.Program `ebpf:"xl_pod_out"`
	XlPodhostOut *ebpf.Program `ebpf:"xl_podhost_out"`
}

func (p *phantomPrograms) Close() error {
	return _PhantomClose(
		p.XlHostIn,
		p.XlHostLocal,
		p.XlHostOut,
		p.XlPodIn,
		p.XlPodOut,
		p.XlPodhostOut,
	)
}

func _PhantomClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed phantom_bpfel.o
var _PhantomBytes []byte
